import {
  Box,
  Button,
  Center,
  Flex,
  Input,
  InputRightElement,
  Text,
  InputGroup,
} from "@chakra-ui/react";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Navbar from "../components/Navbar";
import { PropagateLoader } from "react-spinners";
import Line from "../components/Line";
import strategies from "../utils/strategies";
import StrategyButton from "../components/StrategyButton";

const Login = () => {
  const [show, setShow] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleClick = () => setShow(!show);

  const handleSignup = () => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 5000);
  };
  return (
    <Box>
      <Head>
        <title>Login - Phollio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Flex
        alignItems={"center"}
        justifyContent={"center"}
        flexDirection={"column"}
      >
        <Text fontSize={"4xl"} textAlign={"center"}>
          Welcome back
        </Text>
        <Box w={"350px"}>
          <Input placeholder="Username or email" my={2} />
          <InputGroup size="md" my={2}>
            <Input
              pr="4.5rem"
              type={show ? "text" : "password"}
              placeholder="Enter password"
            />
            <InputRightElement width="4.5rem">
              <Button h="1.75rem" size="sm" onClick={handleClick}>
                {show ? "Hide" : "Show"}
              </Button>
            </InputRightElement>
          </InputGroup>
          <Button
            w={"350px"}
            my={2}
            borderRadius={"3xl"}
            backgroundColor={"brand.accent"}
            _hover={{
              opacity: 0.8,
            }}
            onClick={handleSignup}
            disabled={loading}
          >
            {loading ? <PropagateLoader color="#fff" /> : "Login"}
          </Button>
        </Box>
        <Flex flexDirection={"column"} alignItems={"center"} mt={3}>
          <Line text={"login"} />
          <Flex alignItems={"center"} gap={3} my={2}>
            {strategies.map((strategy) => (
              <StrategyButton icon={strategy.icon} />
            ))}
          </Flex>
        </Flex>
      </Flex>
    </Box>
  );
};

export default Login;
